require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Gemfile'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'config/initializers/redis.rb'
    - 'lib/redis_store.rb'
