AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 110

Style/Documentation:
  Exclude:
    - '**/*'

Style/GlobalVars:
  Exclude:
    - 'config/initializers/redis.rb'
    - 'lib/redis_store.rb'
