language: ruby
rvm:
  - 2.4.0
bundler_args: --jobs=2
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:setup
  - bundle exec rake spec
  - cat /home/travis/build/BaiBianX/insight/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/.rubocop.yml
  - bundle exec rubocop --config .rubocop.yml
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"

