default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: insight_development
  username: insight
  password:

test:
  <<: *default
  database: insight_test

production:
  <<: *default
  database: insight_production
  username: insight
  password: <%= ENV['INSIGHT_DATABASE_PASSWORD'] %>
